/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();
cleanupOutdatedCaches();

// Precache all assets generated by build tool
precacheAndRoute(self.__WB_MANIFEST);

// Listen for Web Push events
self.addEventListener('push', (event: PushEvent) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const title = data.title || 'Tezā Notification';
    interface ExtendedNotificationOptions extends NotificationOptions {
      vibrate?: number[];
      renotify?: boolean;
      tag?: string;
    }

    const options: ExtendedNotificationOptions = {
      body: data.body || '',
      icon: data.icon || '/pwa-192x192.png',
      badge: data.badge || '/favicon-32x32.png',
      data: {
        url: data.url || '/',
        type: data.type || 'system',
        ...data.data,
      },
      vibrate: [100, 50, 100],
      tag: data.type ? `teza-${data.type}-${Date.now()}` : `teza-push-${Date.now()}`,
      renotify: true,
    };

    event.waitUntil(self.registration.showNotification(title, options));
  } catch (err) {
    console.error('[ServiceWorker] Push event parsing error:', err);
    // Fallback if push payload is plain text
    const textData = event.data.text();
    event.waitUntil(
      self.registration.showNotification('Tezā Update', {
        body: textData,
        icon: '/pwa-192x192.png',
        badge: '/favicon-32x32.png',
        data: { url: '/' },
      })
    );
  }
});

// Handle notification click action
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();

  const targetUrl = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.focus();
          if ('navigate' in client && targetUrl !== '/') {
            client.navigate(targetUrl);
          }
          return;
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl);
      }
    })
  );
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
